import math
import random

class StructuralBiophysicistAgent:
    def __init__(self):
        self.name = "Structural Biophysicist Agent"
        # Standard three-letter code mapping
        self.aa_mapping = {
            'A': 'ALA', 'R': 'ARG', 'N': 'ASN', 'D': 'ASP', 'C': 'CYS',
            'Q': 'GLN', 'E': 'GLU', 'G': 'GLY', 'H': 'HIS', 'I': 'ILE',
            'L': 'LEU', 'K': 'LYS', 'M': 'MET', 'F': 'PHE', 'P': 'PRO',
            'S': 'SER', 'T': 'THR', 'W': 'TRP', 'Y': 'TYR', 'V': 'VAL'
        }

    def generate_helical_pdb(self, sequence: str) -> str:
        """
        Generates a valid PDB string representing an alpha-helix structure of the peptide
        surrounded by a simulated lipid membrane bilayer (POPG/POPE headgroups).
        """
        pdb_lines = []
        atom_serial = 1
        
        # Alpha-helix parameters
        R_ca = 2.3  # Radius of CA helix
        d_ca = 1.5  # Rise per residue along Z axis
        phi_per_res = math.radians(100.0)  # 100 degrees rotation per residue

        # Center the peptide in the box
        # Total length in Z is (N-1) * 1.5. Center it at Z = 0
        n_res = len(sequence)
        z_offset = -((n_res - 1) * d_ca) / 2.0

        pdb_lines.append(f"HEADER    DE NOVO AMP ALPHA-HELIX STRUCTURE - GENERATED BY CRYPTAM")
        pdb_lines.append(f"TITLE     PEPTIDE: {sequence}")
        
        for idx, aa in enumerate(sequence):
            res_num = idx + 1
            res_name = self.aa_mapping.get(aa.upper(), 'ALA')
            
            # Calculate angle for this residue
            theta = idx * phi_per_res
            
            # Backbone atom positions (rough parametric approximations for an alpha-helix)
            # CA (Alpha Carbon)
            ca_x = R_ca * math.cos(theta)
            ca_y = R_ca * math.sin(theta)
            ca_z = idx * d_ca + z_offset
            
            # N (Nitrogen) - slightly rotated back and down
            n_theta = theta - 0.7
            n_x = 2.1 * math.cos(n_theta)
            n_y = 2.1 * math.sin(n_theta)
            n_z = idx * d_ca - 0.5 + z_offset
            
            # C (Carbonyl Carbon) - slightly rotated forward and up
            c_theta = theta + 0.7
            c_x = 2.1 * math.cos(c_theta)
            c_y = 2.1 * math.sin(c_theta)
            c_z = idx * d_ca + 0.5 + z_offset
            
            # O (Carbonyl Oxygen) - further out from C
            o_theta = theta + 1.2
            o_x = 3.0 * math.cos(o_theta)
            o_y = 3.0 * math.sin(o_theta)
            o_z = idx * d_ca + 0.8 + z_offset
            
            # Side chain CB (Beta Carbon) - pointing outward radially
            cb_x = 3.3 * math.cos(theta)
            cb_y = 3.3 * math.sin(theta)
            cb_z = idx * d_ca + z_offset

            # Format PDB ATOM lines
            # N
            pdb_lines.append(f"ATOM  {atom_serial:5d}  N   {res_name} A{res_num:4d}    {n_x:8.3f}{n_y:8.3f}{n_z:8.3f}  1.00 20.00           N")
            atom_serial += 1
            # CA
            pdb_lines.append(f"ATOM  {atom_serial:5d}  CA  {res_name} A{res_num:4d}    {ca_x:8.3f}{ca_y:8.3f}{ca_z:8.3f}  1.00 20.00           C")
            atom_serial += 1
            # C
            pdb_lines.append(f"ATOM  {atom_serial:5d}  C   {res_name} A{res_num:4d}    {c_x:8.3f}{c_y:8.3f}{c_z:8.3f}  1.00 20.00           C")
            atom_serial += 1
            # O
            pdb_lines.append(f"ATOM  {atom_serial:5d}  O   {res_name} A{res_num:4d}    {o_x:8.3f}{o_y:8.3f}{o_z:8.3f}  1.00 20.00           O")
            atom_serial += 1
            # CB (unless it's Glycine)
            if res_name != 'GLY':
                pdb_lines.append(f"ATOM  {atom_serial:5d}  CB  {res_name} A{res_num:4d}    {cb_x:8.3f}{cb_y:8.3f}{cb_z:8.3f}  1.00 20.00           C")
                atom_serial += 1
                
        # HELIX record to tell 3Dmol.js it is an alpha-helix explicitly
        pdb_lines.append(f"HELIX    1   1 THR A    1 LEU A {n_res:4d}  1                                  {n_res:4d}")
        
        # Add Simulated Membrane Bilayer (POPG / POPE Lipid headgroups)
        # We will represent headgroups using Phosphorus (P) and Nitrogen (N) atoms
        # Placed as grids in two leaflets: Upper at Z = 12.0, Lower at Z = -12.0
        pdb_lines.append("REMARK    SIMULATED MEMBRANE BILAYER (POPE/POPG HEADGROUPS)")
        
        lipid_res_num = n_res + 2
        for z_val, leaflet in [(12.0, "UP"), (-12.0, "LO")]:
            for x_idx in range(-3, 4):
                for y_idx in range(-3, 4):
                    # Introduce a slight noise to make it look realistic (fluid membrane)
                    x = x_idx * 7.0 + random.uniform(-1.0, 1.0)
                    y = y_idx * 7.0 + random.uniform(-1.0, 1.0)
                    z = z_val + random.uniform(-0.5, 0.5)
                    
                    # Alternate between POPE (Phosphatidylethanolamine) and POPG (Phosphatidylglycerol)
                    is_pe = (x_idx + y_idx) % 2 == 0
                    lipid_name = "POPE" if is_pe else "POPG"
                    
                    # Phosphorus atom
                    pdb_lines.append(f"ATOM  {atom_serial:5d}  P   {lipid_name} B{lipid_res_num:4d}    {x:8.3f}{y:8.3f}{z:8.3f}  1.00 40.00           P")
                    atom_serial += 1
                    
                    # Choline/Ethanolamine Nitrogen or Glycerol Oxygen (offset by 2A in Z away from center)
                    offset_z = z + (2.0 if z_val > 0 else -2.0)
                    atom_name = "N" if is_pe else "O"
                    pdb_lines.append(f"ATOM  {atom_serial:5d}  {atom_name}   {lipid_name} B{lipid_res_num:4d}    {x:8.3f}{y:8.3f}{offset_z:8.3f}  1.00 40.00           {atom_name}")
                    atom_serial += 1
                    
                    lipid_res_num += 1
                    
        pdb_lines.append("END")
        return "\n".join(pdb_lines)

    def generate_martini_mdp(self, peptide_id: str) -> str:
        """Generates GROMACS MDP parameter file for Coarse-Grained Martini MD simulation."""
        return f"""; GROMACS Martini MDP File - Generated by CRYPTAM for candidate {peptide_id}
define                   = -DPOSRES_FC=1000
integrator               = md
tinit                    = 0.0
dt                       = 0.020    ; 20 fs time step
nsteps                   = 5000000  ; 100 ns simulation

; Neighbor searching
cutoff-scheme            = Verlet
nstlist                  = 20
ns-type                  = Grid
pbc                      = xyz
rlist                    = 1.1

; Electrostatics
coulombtype              = reaction-field
rcoulomb                 = 1.1
epsilon_r                = 15       ; Screening for Martini water
epsilon_rf               = 0
vdw_type                 = cutoff
vdw-modifier             = Potential-shift-verlet
rvdw                     = 1.1

; Temperature coupling
tcoupl                   = v-rescale
tc-grps                  = Protein POPG_POPE W_ION
tau-t                    = 1.0  1.0  1.0
ref-t                    = 310  310  310    ; Eukaryotic/Bacterial physiological temp

; Pressure coupling
pcoupl                   = parrinello-rahman
pcoupltype               = semiisotropic
tau-p                    = 12.0
compressibility          = 3e-4  3e-4
ref-p                    = 1.0   1.0        ; 1 bar atmosphere

; Output control
nstxout-compressed       = 5000     ; Save coordinates every 100 ps
"""

    def generate_martini_topology(self, sequence: str) -> str:
        """Generates GROMACS Topology (.top) file for Martini coarse-grained model."""
        return f"""; GROMACS Martini Topology File - Generated by CRYPTAM
#include "martini_v3.0.0.itp"
#include "martini_v3.0.0_proteins.itp"
#include "martini_v3.0.0_lipids.itp"
#include "martini_v3.0.0_ions.itp"

[ system ]
; name
CRYPTAM In Silico Membrane Insertion Simulation for: {sequence}

[ molecules ]
; name        number
Protein_A     1
POPE          128
POPG          32
W             3200
NA+           38
CL-           24
"""

    def run_docking_simulation(self, peptide_seq: str, target: str):
        """Simulates HDOCK/HADDOCK docking against antibiotic resistance targets."""
        logs = []
        logs.append(f"[Biophysicist] Initializing macromolecular docking of peptide against target: {target}")
        
        # Determine affinity parameters depending on sequence charge and hydrophobic density
        charge = sum(1 for aa in peptide_seq if aa in ['K', 'R']) - sum(1 for aa in peptide_seq if aa in ['D', 'E'])
        
        # Docking scoring heuristics
        base_energy = -180.0 # Standard HDOCK docking score
        
        if target == "Lipid-II Precursor (Cell Wall)":
            # Lipid-II is highly negative (pyrophosphate group), binds highly cationic peptides (e.g. vancomycin, nisin)
            affinity = -180.0 - (charge * 18.5) + random.uniform(-10.0, 10.0)
            k_d = 10 ** (affinity / 30.0) * 1000.0 # nM range
            interface_residues = "PP-group, MurNAc, D-Ala3, D-Ala4"
        elif target == "TEM-1 Beta-Lactamase (Resonance Enzyme)":
            # Protein target, requires steric fit and key hydrogen bonds
            affinity = -210.0 - (len(peptide_seq) * 2.1) + random.uniform(-15.0, 15.0)
            k_d = 10 ** (affinity / 35.0) * 1000.0
            interface_residues = "Glu166, Ser70, Lys73, Ala237"
        else:
            affinity = -150.0 + random.uniform(-20.0, 20.0)
            k_d = 5000.0
            interface_residues = "Non-specific binding"
            
        logs.append(f"[Biophysicist] HDOCK grid search computed 10,000 orientations.")
        logs.append(f"[Biophysicist] Best docking pose energy: {affinity:.2f} kcal/mol (Estimated Kd: {k_d:.2f} nM)")
        
        return {
            "logs": logs,
            "docking_score": round(affinity, 2),
            "est_kd_nm": round(k_d, 2),
            "interface_residues": interface_residues,
            "hydrogen_bonds": random.randint(3, 8)
        }

    def run_membrane_simulation(self, peptide_seq: str):
        """Simulates Martini GROMACS membrane insertion statistics."""
        logs = []
        logs.append(f"[Biophysicist] Setting up coarse-grained Martini systems...")
        logs.append(f"[Biophysicist] Built POPE:POPG (3:1) bacterial inner membrane bilayer patch (10x10nm).")
        logs.append(f"[Biophysicist] Placed peptide in solvent. Solvated with Martini water beads + 150mM NaCl.")
        logs.append(f"[Biophysicist] Energy minimized with steepest descent. Max force < 10.0 kJ/mol/nm.")
        
        # Calculate membrane insertion metrics based on hydrophobicity and charge
        # Highly hydrophobic/amphipathic inserts well.
        h_moment = sum(1 for aa in peptide_seq if aa in ['L', 'I', 'V', 'F', 'W']) / len(peptide_seq)
        
        # Biophysical metrics
        free_energy_ins = -15.0 - (h_moment * 40.0) + random.uniform(-3.0, 3.0) # Delta G of insertion in kcal/mol
        scd_order = 0.35 - (h_moment * 0.15) # Lipid order parameter (lower means more disruption/packing leakage)
        lipid_leakage = round(h_moment * 85.0 + random.uniform(0, 10), 1) # % leakage of dye/ions
        
        logs.append(f"[Biophysicist] MD simulation running for 100 ns (5,000,000 steps)...")
        logs.append(f"[Biophysicist] Peptide partition reached equilibrium at t = 35 ns.")
        logs.append(f"[Biophysicist] Free Energy of Insertion (ΔG_ins): {free_energy_ins:.2f} kcal/mol.")
        logs.append(f"[Biophysicist] Lipid packing order disruption (S_CD) observed. Packing index: {scd_order:.3f}")
        
        return {
            "logs": logs,
            "free_energy_insertion_kcal_mol": round(free_energy_ins, 2),
            "lipid_order_disruption_scd": round(scd_order, 3),
            "membrane_leakage_pct": lipid_leakage,
            "structure_pdb": self.generate_helical_pdb(peptide_seq)
        }
